#!/usr/bin/env bash

# commits new node definitions in separate commits
#
# Usage: script/commit-definitions
#
# Notes: extracted from https://github.com/nodenv/node-build-update-defs/blob/ac8e155cd8df843ca224c45ef55a36e20719bf9d/script/submit-definitions

git ls-files --others --exclude-standard -- share/node-build |
while read -r node_def; do
  node_name=${node_def##*/}
  git add -- "$node_def"
  git commit --quiet --message "$node_name" --message "Created with \`npm run submit-definitions\`." --only -- "$node_def"
  echo "$node_name"
done
