#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

cat <<-MSG
====================
${npm_package_name-} caveats:

For \`node-build\`/\`nodenv install\` to pick up definitions provided by this plugin,
ensure '$PWD/share/node-build' exists in NODE_BUILD_DEFINITIONS.
    export NODE_BUILD_DEFINITIONS="$PWD/share/node-build"
====================
MSG
