#! /usr/bin/env node

var scrape = require('../lib/scraper')

var nodejs = require('../lib/scraper-nodejs')

var nodes = {}
var options = {
  dryRun: false,
  overwrite: false,
  definitionPaths: (process.env.NODE_BUILD_DEFINITIONS || 'share/node-build').split(':')
}

process.argv.forEach(function (arg) {
  switch (arg) {
    case '-f':
    case '--force':
      options.overwrite = true
      break
    case '-n':
    case '--dry-run':
      options.dryRun = true
      break
    case '--nodejs':
      nodes.nodejs = nodejs
      break
  }
})

if (!Object.keys(nodes).length) {
  nodes = { nodejs: nodejs }
}

for (var node in nodes) {
  if (nodes.hasOwnProperty(node)) {
    scrape(nodes[node], options)
  }
}
