#! /usr/bin/env node

const scrape = require('../lib/scraper')

const nodejs = require('../lib/scraper-nodejs')
const nodejsPre = require('../lib/scraper-nodejs-pre')

const nodesToScrape = []
const options = {
  dryRun: false,
  overwrite: false,
  definitionPaths: (
    process.env.NODE_BUILD_DEFINITIONS || 'share/node-build'
  ).split(':')
}

process.argv.forEach(function(arg) {
  switch (arg) {
    case '-f':
    case '--force':
      options.overwrite = true
      break
    case '-n':
    case '--dry-run':
      options.dryRun = true
      break
    case '--nodejs':
      nodesToScrape.push(nodejs)
      break
    case '--nodejs-pre':
      nodesToScrape.push(nodejsPre)
      break
  }
})

if (!nodesToScrape.length) {
  nodesToScrape.push(nodejs)
}

nodesToScrape.forEach(function(node) {
  scrape(node, options)
})
