#! /usr/bin/env node

const DefinitionFile = require('../lib/definition-file')
const NodejsOrgScraper = require('../lib/scraper-nodejs_org')

const nodejs = new NodejsOrgScraper({
  displayName: 'nodejs',
  baseUri: 'https://nodejs.org/dist/'
})

const nodejsPre = new NodejsOrgScraper({
  displayName: 'nodejs release candidate',
  baseUri: 'https://nodejs.org/download/rc/'
})

const chakracore = new NodejsOrgScraper({
  name: 'chakracore',
  baseUri: 'https://nodejs.org/download/chakracore-release/'
})

const scrapers = []
const options = {
  dryRun: false,
  overwrite: false,
  definitionPaths: (
    process.env.NODE_BUILD_DEFINITIONS || 'share/node-build'
  ).split(':')
}

process.argv.forEach(arg => {
  switch (arg) {
    case '-f':
    case '--force':
      options.overwrite = true
      break
    case '-n':
    case '--dry-run':
      options.dryRun = true
      break
    case '--nodejs':
      scrapers.push(nodejs)
      break
    case '--nodejs-pre':
      scrapers.push(nodejsPre)
      break
    case '--chakracore':
      scrapers.push(chakracore)
      break
  }
})

if (!scrapers.length) {
  scrapers.push(nodejs)
}

DefinitionFile.configure(options)

scrapers.forEach(scraper => scraper.scrape())
